package code_generator;


//----------------------------------------------------
//The following code was generated by CUP v0.11a beta 20060608
//Thu May 03 23:59:59 EDT 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
/* terminals */
public static final int DIVIDE = 26;
public static final int RIGHT_PAREN = 41;
public static final int T = 47;
public static final int OUTPUT = 14;
public static final int UMINUS = 2;
public static final int INPUT = 13;
public static final int SEMI = 42;
public static final int INFILEOPEN = 7;
public static final int LESS = 33;
public static final int FOR = 11;
public static final int MINUS = 24;
public static final int F = 48;
public static final int NOT = 39;
public static final int AND = 38;
public static final int big = 21;
public static final int INFILECLOSE = 8;
public static final int OR = 37;
public static final int OUTFILECLOSE = 10;
public static final int LEFT_BRACE = 44;
public static final int COMMA = 43;
public static final int BOOL = 4;
public static final int file = 22;
public static final int PLUS = 23;
public static final int ASSIGN = 30;
public static final int IF = 12;
public static final int RIGHT_BRKT = 29;
public static final int FILEINPUT = 18;
public static final int EOF = 0;
public static final int RETURN = 15;
public static final int GTR = 32;
public static final int EQUAL = 31;
public static final int error = 1;
public static final int LEFT_BRKT = 28;
public static final int RIGHT_BRACE = 45;
public static final int MOD = 27;
public static final int VOID = 17;
public static final int small = 46;
public static final int TIMES = 25;
public static final int ELSE = 5;
public static final int NOT_EQ = 36;
public static final int FILE = 6;
public static final int OUTFILEOPEN = 9;
public static final int SMALL = 16;
public static final int LESS_EQ = 35;
public static final int BIG = 3;
public static final int LEFT_PAREN = 40;
public static final int FILEOUTPUT = 19;
public static final int GTR_EQ = 34;
public static final int IDENTIFIER = 20;
}


